trigger:
- main
pool:
  vmImage: ubuntu-latest
steps:
- task: NeuVectorScan@2
  inputs:
    scanType: 'external'
    neuvectorScanner: 'nv-gke'
    containerRegistry: 'dockeregistry'
    repository: 'nvlab/alpine'
    tag: '*'


